# CI workflow specifically for the access module
name: Access Module CI

on:
  push:
    branches: [ main, master ]
    paths:
      - 'access/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'access/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build and test access module
      run: ./gradlew :access:clean :access:build :access:test
      
    - name: Generate Javadoc for access module
      run: ./gradlew :access:javadoc || true
      
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: access/build/reports/tests/
        
    - name: Upload Javadoc
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: javadoc
        path: access/build/docs/javadoc/ 