# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      
    - name: build and test cadc-permissions
      run: cd cadc-permissions && ../gradlew --info clean build javadoc install
      
    - name: build and test cadc-permissions-client
      run: cd cadc-permissions-client && ../gradlew --info clean build javadoc install
      
    - name: build and test cadc-gms
      run: cd cadc-gms && ../gradlew --info clean build javadoc install
      
    - name: build and test cadc-access-control
      run: cd cadc-access-control && ../gradlew --info clean build javadoc install
      
    - name: build and test cadc-access-control-server
      run: cd cadc-access-control-server && ../gradlew --info clean build javadoc install
      
    - name: build and test cadc-access-control
      run: cd cadc-access-control && ../gradlew --info clean build javadoc install

    - name: build and test posix-mapper
      run: cd posix-mapper && ../gradlew --info clean build javadoc
